var content = [
    {
      "Brisbane": "Acacia Ridge",
      "Logan": "Bahrs Scrub",
      "Urban Ipswich": "Augustine Heights",
      "Rural Ipswich": "Amberley",
      "Moreton Bay Region": "Albany Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Albion",
      "Logan": "Bannockburn",
      "Urban Ipswich": "Barellan Point",
      "Rural Ipswich": "Ashwell",
      "Moreton Bay Region": "Arana Hills",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Alderley",
      "Logan": "Beenleigh",
      "Urban Ipswich": "Basin Pocket",
      "Rural Ipswich": "Calvert",
      "Moreton Bay Region": "Armstrong Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Algester",
      "Logan": "Belivah",
      "Urban Ipswich": "Bellbird Park",
      "Rural Ipswich": "Deebing Heights",
      "Moreton Bay Region": "Banksia Beach",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Annerley",
      "Logan": "Berrinba",
      "Urban Ipswich": "Blacksoil",
      "Rural Ipswich": "Ebenezer",
      "Moreton Bay Region": "Beachmere",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Anstead",
      "Logan": "Bethania",
      "Urban Ipswich": "Blackstone",
      "Rural Ipswich": "Goolman",
      "Moreton Bay Region": "Bellara",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Archerfield",
      "Logan": "Boronia Heights",
      "Urban Ipswich": "Booval",
      "Rural Ipswich": "Grandchester",
      "Moreton Bay Region": "Bellmere",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Ascot",
      "Logan": "Browns Plains",
      "Urban Ipswich": "Brassall",
      "Rural Ipswich": "Haigslea",
      "Moreton Bay Region": "Bellthorpe",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Ashgrove",
      "Logan": "Buccan",
      "Urban Ipswich": "Brookwater",
      "Rural Ipswich": "Ironbark",
      "Moreton Bay Region": "Bongaree",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Aspley",
      "Logan": "Carbrook",
      "Urban Ipswich": "Bundamba",
      "Rural Ipswich": "Jeebropilly",
      "Moreton Bay Region": "Bracalba",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Auchenflower",
      "Logan": "Cedar Creek",
      "Urban Ipswich": "Carole Park",
      "Rural Ipswich": "Lanefield",
      "Moreton Bay Region": "Bray Park",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bald Hills",
      "Logan": "Cedar Grove",
      "Urban Ipswich": "Camira",
      "Rural Ipswich": "Limestone Ridges",
      "Moreton Bay Region": "Brendale",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Balmoral",
      "Logan": "Cedar Vale",
      "Urban Ipswich": "Churchill",
      "Rural Ipswich": "Marburg",
      "Moreton Bay Region": "Bunya",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Banks Creek",
      "Logan": "Chambers Flat",
      "Urban Ipswich": "Chuwar",
      "Rural Ipswich": "Mount Forbes",
      "Moreton Bay Region": "Burpengary",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Banyo",
      "Logan": "Cornubia",
      "Urban Ipswich": "Coalfalls",
      "Rural Ipswich": "Mount Marrow",
      "Moreton Bay Region": "Burpengary East",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bardon",
      "Logan": "Crestmead",
      "Urban Ipswich": "Collingwood Park",
      "Rural Ipswich": "Mutdapilly",
      "Moreton Bay Region": "Caboolture",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bellbowrie",
      "Logan": "Daisy Hill",
      "Urban Ipswich": "Dinmore",
      "Rural Ipswich": "Peak Crossing",
      "Moreton Bay Region": "Caboolture South",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Belmont",
      "Logan": "Eagleby",
      "Urban Ipswich": "East Ipswich",
      "Rural Ipswich": "Pine Mountain",
      "Moreton Bay Region": "Camp Mountain",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Boondall",
      "Logan": "Edens Landing",
      "Urban Ipswich": "Eastern Heights",
      "Rural Ipswich": "Purga",
      "Moreton Bay Region": "Campbells Pocket",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bowen Hills",
      "Logan": "Forestdale",
      "Urban Ipswich": "Ebenezer",
      "Rural Ipswich": "Rosewood",
      "Moreton Bay Region": "Cashmere",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bracken Ridge",
      "Logan": "Greenbank",
      "Urban Ipswich": "Ebbw Vale",
      "Rural Ipswich": "South Ripley",
      "Moreton Bay Region": "Cedar Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Brendale",
      "Logan": "Heritage Park",
      "Urban Ipswich": "Flinders View",
      "Rural Ipswich": "Spring Mountain",
      "Moreton Bay Region": "Cedarton",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bridgeman Downs",
      "Logan": "Hillcrest",
      "Urban Ipswich": "Gailes",
      "Rural Ipswich": "Tallegalla",
      "Moreton Bay Region": "Clear Mountain",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Brighton",
      "Logan": "Holmview",
      "Urban Ipswich": "Goodna",
      "Rural Ipswich": "Thagoona",
      "Moreton Bay Region": "Clontarf",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Brisbane Airport",
      "Logan": "Jimboomba",
      "Urban Ipswich": "Haigslea",
      "Rural Ipswich": "The Bluff",
      "Moreton Bay Region": "Closeburn",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Brisbane City",
      "Logan": "Kagaru",
      "Urban Ipswich": "Ipswich",
      "Rural Ipswich": "Walloon",
      "Moreton Bay Region": "Commissioners Flat",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Brookfield",
      "Logan": "Kingston",
      "Urban Ipswich": "Karalee",
      "Rural Ipswich": "White Rock",
      "Moreton Bay Region": "D'Aguilar",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bulimba",
      "Logan": "Logan Central",
      "Urban Ipswich": "Karrabin",
      "Rural Ipswich": "Willowbank",
      "Moreton Bay Region": "Dakabin",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bulwer",
      "Logan": "Logan Reserve",
      "Urban Ipswich": "Leichhardt",
      "Rural Ipswich": "Woolshed",
      "Moreton Bay Region": "Dayboro",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Bunya",
      "Logan": "Logan Village",
      "Urban Ipswich": "Moores Pocket",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Deception Bay",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Burbank",
      "Logan": "Loganholme",
      "Urban Ipswich": "Muirlea",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Delaneys Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Calamvale",
      "Logan": "Loganlea",
      "Urban Ipswich": "New Chum",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Donnybrook (Qld)",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Camp Hill",
      "Logan": "Lyons",
      "Urban Ipswich": "Newtown",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Draper",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Cannon Hill",
      "Logan": "Marsden",
      "Urban Ipswich": "North Booval",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Eatons Hill",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Carina",
      "Logan": "Meadowbrook",
      "Urban Ipswich": "North Ipswich",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Elimbah",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Carina Heights",
      "Logan": "Mount Warren Park",
      "Urban Ipswich": "North Tivoli",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Everton Hills",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Carindale",
      "Logan": "Mundoolun",
      "Urban Ipswich": "One Mile",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Ferny Hills",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Carseldine",
      "Logan": "Munruben",
      "Urban Ipswich": "Raceview",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Godwin Beach",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Cashmere",
      "Logan": "New Beith",
      "Urban Ipswich": "Redbank",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Griffin",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Chandler",
      "Logan": "North Maclean",
      "Urban Ipswich": "Redbank Plains",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Highvale",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Chapel Hill",
      "Logan": "Park Ridge South",
      "Urban Ipswich": "Ripley",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Jollys Lookout",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Chelmer",
      "Logan": "Park Ridge",
      "Urban Ipswich": "Riverview",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Joyner",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Chermside",
      "Logan": "Priestdale",
      "Urban Ipswich": "Rosewood",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Kallangur",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Chermside West",
      "Logan": "Regents Park",
      "Urban Ipswich": "Sadliers Crossing",
      "Rural Ipswich": "",
      "Moreton Bay Region": "King Scrub",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Chuwar",
      "Logan": "Rochedale South",
      "Urban Ipswich": "Silkstone",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Kippa-Ring",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Clayfield",
      "Logan": "Shailer Park",
      "Urban Ipswich": "Springfield",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Kobble Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Clear Mountain",
      "Logan": "Slacks Creek",
      "Urban Ipswich": "Springfield Central",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Kurwongbah",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": "On Map"
    },
    {
      "Brisbane": "Coopers Plains",
      "Logan": "South Maclean",
      "Urban Ipswich": "Springfield Lakes",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Laceys Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Coorparoo",
      "Logan": "Springwood",
      "Urban Ipswich": "Swanbank",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Lawnton",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Corinda",
      "Logan": "Stockleigh",
      "Urban Ipswich": "Tivoli",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mango Hill",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Cowan Cowan",
      "Logan": "Tamborine",
      "Urban Ipswich": "West Ipswich",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Margate",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Darra",
      "Logan": "Tanah Merah",
      "Urban Ipswich": "Woodend",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Meldale",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Deagon",
      "Logan": "Underwood",
      "Urban Ipswich": "Wulkuraka",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Moodlu",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Doolandella",
      "Logan": "Undullah",
      "Urban Ipswich": "Yamanto",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Moorina",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Drewvale",
      "Logan": "Veresdale Scrub",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Morayfield",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Durack",
      "Logan": "Veresdale",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mount Delaney",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Dutton Park",
      "Logan": "Waterford West",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mount Glorious",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Eagle Farm",
      "Logan": "Tweed Heads",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mount Mee",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "East Brisbane",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mount Nebo",
      "": "",
      "__1": "",
      "__2": "On Map",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Eatons Hill",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mount Pleasant",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Eight Mile Plains",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Mount Samson",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Ellen Grove",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Murrumba Downs",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "England Creek",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Narangba",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Enoggera",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Neurum",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Enoggera Reservoir",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Newport",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Everton Park",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Ningi",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Fairfield",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "North Lakes",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Ferny Grove",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Ocean View",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Ferny Hills",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Petrie",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Fig Tree Pocket",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Redcliffe",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Fitzgibbon",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Rocksberg",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Forest Lake",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Rothwell",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Fortitude Valley",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Rush Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Gaythorne",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Samford Valley",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Geebung",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Samford Village",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Gordon Park",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Samsonvale",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Graceville",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Sandstone Point",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Grange",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Scarborough",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Green Island",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Stanmore",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Greenslopes",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Stony Creek",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Gumdale",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Strathpine",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Hamilton",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Toorbul",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Hawthorne",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Upper Caboolture",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Heathwood",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Wamuran",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Hemmant",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Wamuran Basin",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Hendra",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Warner",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Herston",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "White Patch",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Highgate Hill",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Whiteside",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Holland Park",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Wights Mountain",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Holland Park West",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Woodford",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Inala",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Woody Point",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Indooroopilly",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Woorim",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Jamboree Heights",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "Yugar",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Jindalee",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Joyner",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kalinga",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kallangur",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kangaroo Point",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Karana Downs",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Karawatha",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kedron",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kelvin Grove",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kenmore",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kenmore Hills",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Keperra",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kholo",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kooringal",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Kuraby",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Lake Manchester",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Larapinta",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Lota",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Lutwyche",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Lytton",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Macgregor",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mackenzie",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Manly",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Manly West",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mansfield",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "McDowall",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Middle Park",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Milton",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mitchelton",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Moggill",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Moorooka",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Moreton Island",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Morningside",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mt Coot-tha",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mt Crosby",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mt Gravatt",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mt Gravatt East",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mt Ommaney",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Mud Island",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Murarrie",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Murrumba Downs",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Nathan",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "New Farm",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Newmarket",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Newstead",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Norman Park",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "North Brisbane",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Northgate",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Nudgee",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Nudgee Beach",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Nundah",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Oxley",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Paddington",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Pallara",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Parkinson",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Petrie Terrace",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Pinjarra Hills",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Pinkenba",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Port of Brisbane",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Pullenvale",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Ransome",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Red Hill",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Richlands",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Riverhills",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Robertson",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Rochedale",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Rocklea",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Runcorn",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Salisbury",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Samford Village",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Sandgate",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Seven Hills",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Seventeen Mile Rocks",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Sherwood",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Shorncliffe",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Sinnamon Park",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "South Brisbane",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "South Brisbane",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Spring Hill",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "St Helena Island",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "St Lucia",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Stafford",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Stafford Heights",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Stones Corner",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Stretton",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Sumner",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Sunnybank",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Sunnybank Hills",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Taigum",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Taringa",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Tarragindi",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Teneriffe",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Tennyson",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "The Gap",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Tingalpa",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Toowong",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Upper Brookfield",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Upper Kedron",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Upper Mt Gravatt",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Virginia",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wacol",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wakerley",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wavell Heights",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "West End",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Westlake",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Willawong",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wilston",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Windsor",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wishart",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Woolloongabba",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wooloowin",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wynnum",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Wynnum West",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Yeerongpilly",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Yeronga",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    },
    {
      "Brisbane": "Zillmere",
      "Logan": "",
      "Urban Ipswich": "",
      "Rural Ipswich": "",
      "Moreton Bay Region": "",
      "": "",
      "__1": "",
      "__2": "",
      "__3": "",
      "__4": ""
    }
  ]

content.forEach(c=>{
    
})